# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/subworkflows/yaml-schema.json
name: hic_bwamem2
description: Placeholder
keywords:
  - bam
  - cram
  - genomics
components:
  - bwamem2/index
  - samtools/merge
  - cram/filteralign
input:
  - reference_tuple:
      description: |
        Placeholder
  - csv_ch:
      description: |
        Placeholder
output:
  - mappedbams:
      description: |
        Placeholder
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"
authors:
  - "@sanger-tol"

